In [8]:
!pip install numpy

In [9]:
import numpy as np

In [10]:
uno = np.random.randint(3,12,size=(5,7))

In [11]:
print(uno.dtype)
print(uno.max())
print(uno.min(axis=1))
print(np.argmin(uno, axis=1))

int32
11
[3 5 4 3 3]
[1 3 1 3 5]


In [12]:
dos = np.arange(4, 100, 5)

In [13]:
print(dos)

[ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99]


In [14]:
tres = np.arange(4,100,5)

In [15]:
print(tres.reshape(4,5))

[[ 4  9 14 19 24]
 [29 34 39 44 49]
 [54 59 64 69 74]
 [79 84 89 94 99]]


In [16]:
cuatro = np.random.normal(size=(3,4,2))

In [17]:
print(cuatro)

[[[-1.47068446 -0.32247038]
  [ 2.00792169  2.6698981 ]
  [-1.58373344  0.24036452]
  [ 1.627437    0.61058473]]

 [[ 0.48936488 -1.78351586]
  [ 1.16088126  1.28363338]
  [ 0.51147613  0.26287902]
  [ 0.21158717 -0.10500064]]

 [[ 0.54915235  0.73423154]
  [ 0.66077564  0.21306227]
  [ 0.22464153  0.70353645]
  [ 1.21611843 -1.68609423]]]


In [18]:
cinco = np.diag(np.ones(4, dtype=int), k=-2)

In [19]:
print(cinco)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]


In [20]:
seis = np.arange(3, 34, 2)

In [21]:
print(seis)
print(seis.size)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]
16


In [22]:
print(seis[-4:])
print(seis[0:16:3])

[27 29 31 33]
[ 3  9 15 21 27 33]


In [23]:
siete =np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])

In [24]:
print(siete[4,5])
print(siete[2:5, 3:5])
print(siete[1:4, :])

72
[[76  3]
 [26 71]
 [38 54]]
[[87 51 13 75 78 46 53]
 [43 24 58 76  3  3 57]
 [84 86 75 26 71 77  7]]


In [25]:
ocho = np.arange(1,50,3)

In [31]:
print(ocho[(ocho > 7) & (ocho < 43)])
print(ocho[(ocho > 11) & (ocho < 45) & (ocho % 2 == 0)])

[10 13 16 19 22 25 28 31 34 37 40]
[16 22 28 34 40]


In [32]:
nueve = np.linspace(0, 1, 20)

In [47]:
media = np.mean(nueve)
print(media)
desv = np.std(nueve)
print(desv)
mediana = np.median(nueve)
print(mediana)
#log = np.log10(nueve) ## este fue un intento fallido
#mlog = np.mean(log)
#print(mlog)

0.5
0.30348848933344197
0.5


In [48]:
nuevee = np.linspace(0, 1, 20) + 1e-10
log = np.log10(nuevee)
mlog = np.mean(log)
print(mlog) #no toy segura de este, pero trate :s

-0.8605611896981283


In [53]:
def diez_f(diez):
    if diez.ndim == 1:
        diez_float = diez.astype(float)[::-1]
        print(diez_float)
    elif diez.ndim == 2:
        diez_flat = diez.flatten()
        print(diez_flat)
    else:
        print("Error :c")

In [57]:
ej_2 = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23])
diez_f(ej_2)

[23. 21. 19. 17. 15. 13. 11.  9.  7.  5.  3.  1.]


In [64]:
matriz_3d = np.array([[[np.random.rand() for k in range(3)] for j in range(3)] for i in range(3)])
print(matriz_3d)
diez_f(matriz_3d)
## este solo es para revisar que funcione bien

[[[0.093102   0.67500837 0.22078936]
  [0.29840295 0.48769695 0.47625727]
  [0.68672921 0.10255903 0.44198496]]

 [[0.62488841 0.18486147 0.84994127]
  [0.32554481 0.28490288 0.88476408]
  [0.00171831 0.0625695  0.46933678]]

 [[0.13849891 0.9723817  0.76393052]
  [0.53446986 0.07240599 0.74276508]
  [0.33741526 0.79818745 0.98566107]]]
Error :c


In [ ]:
#que tenga buen fin, chaito